// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConpressorConfig = { treshold: number, ratio: number, attack_ms: number, release_ms: number, enable: boolean, };
