// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EQConfig = { low_gain: number, mid_gain: number, hight_gain: number, enable: boolean, };
