// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConpressorConfig } from "./ConpressorConfig";
import type { EQConfig } from "./EQConfig";

export type ProcessingConfig = { equalizer: EQConfig, compressor: ConpressorConfig, limiter_treshold: number, master_gain: number, };
